apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-service
  name: zipkin-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: zipkin-service
    spec:
      containers:
      - image: 10.34.0.143/ecommerce/microservice.zipkin.service
        name: zipkin-service
        ports:
        - containerPort: 8905
        resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-service
  name: zipkin-service
spec:
  ports:
  - port: 8905
    targetPort: 8905
  selector:
    io.kompose.service: zipkin-service
status:
  loadBalancer: {}
