version: "3"

services:

  eureka:
    image: ecom/microservice-discovery-eureka
    restart: always
    ports:
      - "8761:8761"

  product-service:
    image: ecom/microservice.product.service
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: msproduct
      DATABASE_USER: msecom
      DATABASE_PASSWORD: msecom
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: msproduct
      MYSQL_USER: msecom
      MYSQL_PASSWORD: msecom
    ports:
      - "3306:3306"