server:
  port: 9411
spring:
  application:
    name: microservice.zipkin.service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true



