apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hystrix-turbine
  name: hystrix-turbine
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hystrix-turbine
    spec:
      containers:
      - image: 10.34.0.143/ecommerce/microservice.hystrix.turbine
        name: hystrix-turbine
        ports:
        - containerPort: 8904
        resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hystrix-turbine
  name: hystrix-turbine
spec:
  ports:
  - port: 8904
    targetPort: 8904
  selector:
    io.kompose.service: hystrix-turbine
status:
  loadBalancer: {}
