server:
  port: 9410
spring:
  application:
    name: microservice.boot.admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true



