server:
  port: 8902
spring:
  application:
    name: microservice.gateway.zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

---
spring:
  profiles: container
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/
