# Use root/example as user/password credentials
version: "3"

services:
  product-service:
      image: 10.34.0.143/ecommerce/microservice.product.service
      environment:
        DATABASE_HOST: mysql-product
        DATABASE_PORT: 3306
        DATABASE_NAME: msproduct
        DATABASE_USER: msecom
        DATABASE_PASSWORD: msecom
      restart: always
      ports:
        - "8002:8002"



    