apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-product
  name: mysql-product
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-product
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: msproduct
        - name: MYSQL_PASSWORD
          value: msecom
        - name: MYSQL_ROOT_PASSWORD
          value: example
        - name: MYSQL_USER
          value: msecom
        image: mysql:5.7
        name: mysql-product
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-product
  name: mysql-product
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mysql-product
status:
  loadBalancer: {}
