apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: product-service
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: mysql-product
        - name: DATABASE_NAME
          value: msproduct
        - name: DATABASE_PASSWORD
          value: msecom
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: msecom
        image: 10.34.0.143/ecommerce/microservice.product.service:0.0.1-SNAPSHOT
        name: product-service
        ports:
        - containerPort: 8002
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  type: NodePort
  ports:
  - port: 8002
    targetPort: 8002
    nodePort: 30002
  selector:
    io.kompose.service: product-service
status:
  loadBalancer: {}
