server:
  port: 8002
spring:
  application:
    name: microservice.product.service
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msecom?createDatabaseIfNotExist=true&useUnicode=true&autoReconnect=true
    username: msecom
    password: msecom
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE