apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway-zuul
  name: gateway-zuul
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway-zuul
    spec:
      containers:
      - image: 10.34.0.143/ecommerce/microservice-gateway-zuul
        name: gateway-zuul
        ports:
        - containerPort: 8902
        resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway-zuul
  name: gateway-zuul
spec:
  ports:
  - port: 8902
    targetPort: 8902
  selector:
    io.kompose.service: gateway-zuul
status:
  loadBalancer: {}
